#!/bin/sh

HOST_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" sp_rails)

# These options are a bad idea. Just used for quick testing.
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
	-i ../keys/docker_ssh root@$HOST_IP
